-- GeoGuard demo data seed for dashboard

-- Risk scores for all 15 zones
INSERT INTO risk_scores_current (zone_id, timestamp, risk_score, risk_level, primary_driver, confidence, recommended_action, recommended_action_ne, rainfall_subscore, ground_condition_subscore, static_risk_subscore, satellite_subscore, soil_moisture_pct, ground_tilt_deg, vibration_g, rainfall_1hr_mm, rainfall_6hr_mm, rainfall_24hr_mm, rainfall_72hr_mm, slope_angle_deg, ndvi_index, deformation_flag) VALUES
('SINDHUPALCHOK-05', NOW(), 82.3, 'CRITICAL', 'Rainfall 72hr accumulated + soil saturation 89%', 0.91, 'Evacuate immediately. All alert channels activated. Auto-report to BIPAD.', 'तत्काल स्थानान्तरण गर्नुहोस्। सबै सूचना माध्यम सक्रिय। BIPAD लाई स्वतः सूचना।', 78.5, 65.2, 72.0, 45.8, 89.2, 5.3, 0.32, 22.5, 45.8, 78.3, 125.6, 42.5, 0.42, true)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('SINDHUPALCHOK-07', NOW(), 68.7, 'HIGH', 'Continuous rainfall 72hr + soil saturation 76%', 0.85, 'Prepare evacuation. WhatsApp alert to ward leaders and police.', 'स्थानान्तरणको तयारी गर्नुहोस्। वडा अधिकारी र प्रहरीलाई WhatsApp सूचना पठाउनुहोस्।', 62.8, 48.5, 55.0, 38.2, 76.5, 3.8, 0.21, 15.2, 32.5, 55.8, 88.6, 38.2, 0.55, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('GORKHA-04', NOW(), 55.8, 'HIGH', '2015 earthquake residual instability + rainfall 72hr', 0.78, 'Prepare evacuation. WhatsApp alert to ward leaders and police.', 'स्थानान्तरणको तयारी गर्नुहोस्। वडा अधिकारी र प्रहरीलाई WhatsApp सूचना पठाउनुहोस्।', 52.5, 35.8, 58.0, 28.5, 72.5, 4.2, 0.18, 12.5, 28.5, 52.3, 78.5, 45.0, 0.48, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

-- MODERATE zones with sensor data
INSERT INTO risk_scores_current VALUES ('KASKI-12', NOW(), 45.3, 'MODERATE', 'Elevated rainfall 24hr + slope angle 35deg', 0.72, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 42.5, 28.0, 52.0, 22.5, 58.2, 1.5, 0.08, 8.5, 18.2, 32.5, 48.6, 35.0, 0.68, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('DHADHING-08', NOW(), 42.8, 'MODERATE', 'Rainfall 24hr accumulated + slope angle', 0.65, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 38.5, 22.0, 45.5, 25.2, 55.8, 1.8, 0.09, 8.2, 18.5, 30.2, 45.5, 32.0, 0.62, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

-- MODERATE zones with satellite-only data (no sensor)
INSERT INTO risk_scores_current VALUES ('MYAGDI-03', NOW(), 38.5, 'MODERATE', 'Satellite rainfall proxy + historical frequency', 0.55, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 35.2, 18.5, 42.0, 25.8, NULL, NULL, NULL, 15.5, 28.5, 42.5, 55.5, 35.5, 0.72, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('NUWAKOT-02', NOW(), 28.5, 'MODERATE', 'Light rainfall + elevated soil moisture', 0.62, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 25.8, 12.5, 35.0, 18.5, 52.5, 1.2, 0.05, 5.5, 12.0, 20.5, 32.5, 28.0, 0.75, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('BAGLUNG-06', NOW(), 32.1, 'MODERATE', 'Moderate rainfall satellite proxy', 0.48, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 30.5, 15.2, 38.5, 20.2, NULL, NULL, NULL, 12.5, 22.0, 35.5, 40.2, 30.0, 0.65, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('TEHRI-02', NOW(), 35.5, 'MODERATE', 'Rainfall satellite proxy + moderate slope', 0.52, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 32.5, 16.8, 40.5, 22.5, NULL, NULL, NULL, 10.5, 20.0, 32.5, 48.5, 30.5, 0.68, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('OKHALDHUNGA-04', NOW(), 30.2, 'MODERATE', 'Light rainfall + moderate slope', 0.58, 'Monitor closely. Alert District EOC.', 'नजिकबाट अवलोकन गर्नुहोस्। जिल्ला EOC लाई सूचना दिनुहोस्।', 28.5, 14.5, 38.0, 20.5, NULL, NULL, NULL, 8.0, 16.5, 25.8, 38.5, 28.5, 0.72, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

-- LOW risk zones
INSERT INTO risk_scores_current VALUES ('RUKUM-01', NOW(), 15.2, 'LOW', 'Satellite-only coverage, no active rainfall', 0.35, 'No action required. Continue routine monitoring.', 'कुनै कार्य आवश्यक छैन। नियमित अवलोकन गर्नुहोस्।', 12.5, 8.0, 22.0, 15.5, NULL, NULL, NULL, 2.5, 5.0, 8.5, 12.5, 25.0, 0.82, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('JAJARKOT-03', NOW(), 18.5, 'LOW', '2023 aftershock zone, low current rainfall', 0.42, 'No action required. Continue routine monitoring.', 'कुनै कार्य आवश्यक छैन। नियमित अवलोकन गर्नुहोस्।', 15.8, 10.5, 25.5, 18.2, NULL, NULL, NULL, 3.2, 6.5, 10.8, 15.5, 28.5, 0.78, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('PALPA-05', NOW(), 12.8, 'LOW', 'Low rainfall, stable conditions', 0.45, 'No action required. Continue routine monitoring.', 'कुनै कार्य आवश्यक छैन। नियमित अवलोकन गर्नुहोस्।', 10.5, 5.2, 18.0, 12.5, NULL, NULL, NULL, 2.0, 4.5, 7.5, 10.5, 22.0, 0.85, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('BHOJPUR-03', NOW(), 20.5, 'LOW', 'Low activity, stable slope conditions', 0.48, 'No action required. Continue routine monitoring.', 'कुनै कार्य आवश्यक छैन। नियमित अवलोकन गर्नुहोस्।', 18.5, 12.0, 25.0, 15.5, NULL, NULL, NULL, 3.5, 7.0, 12.0, 18.0, 26.5, 0.80, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

INSERT INTO risk_scores_current VALUES ('RAMECHAP-01', NOW(), 22.0, 'LOW', 'Near Manthali airport, low current risk', 0.55, 'No action required. Continue routine monitoring.', 'कुनै कार्य आवश्यक छैन। नियमित अवलोकन गर्नुहोस्।', 19.5, 13.5, 28.0, 18.5, NULL, NULL, NULL, 4.0, 8.0, 14.0, 22.5, 24.0, 0.75, false)
ON CONFLICT (zone_id) DO UPDATE SET timestamp=EXCLUDED.timestamp, risk_score=EXCLUDED.risk_score, risk_level=EXCLUDED.risk_level, primary_driver=EXCLUDED.primary_driver, confidence=EXCLUDED.confidence, recommended_action=EXCLUDED.recommended_action, recommended_action_ne=EXCLUDED.recommended_action_ne, rainfall_subscore=EXCLUDED.rainfall_subscore, ground_condition_subscore=EXCLUDED.ground_condition_subscore, static_risk_subscore=EXCLUDED.static_risk_subscore, satellite_subscore=EXCLUDED.satellite_subscore, soil_moisture_pct=EXCLUDED.soil_moisture_pct, ground_tilt_deg=EXCLUDED.ground_tilt_deg, vibration_g=EXCLUDED.vibration_g, rainfall_1hr_mm=EXCLUDED.rainfall_1hr_mm, rainfall_6hr_mm=EXCLUDED.rainfall_6hr_mm, rainfall_24hr_mm=EXCLUDED.rainfall_24hr_mm, rainfall_72hr_mm=EXCLUDED.rainfall_72hr_mm, slope_angle_deg=EXCLUDED.slope_angle_deg, ndvi_index=EXCLUDED.ndvi_index, deformation_flag=EXCLUDED.deformation_flag;

-- Seed alerts for CRITICAL and HIGH zones
INSERT INTO alerts (alert_id, zone_id, timestamp, metric, level, value, threshold_breached, label, label_ne, sensor_id, recommended_action, recommended_action_ne, acknowledged) VALUES
('ALT-CRIT-001', 'SINDHUPALCHOK-05', NOW(), 'rainfall_instant', 'CRITICAL', 55.2, 55.0, 'Instant Rainfall', 'तत्काल वर्षा', 'SN-LD-001', 'Evacuate immediately. All alert channels activated.', 'तत्काल स्थानान्तरण गर्नुहोस्।', false),
('ALT-CRIT-002', 'SINDHUPALCHOK-05', NOW() - INTERVAL '5 minutes', 'tilt', 'CRITICAL', 8.5, 8.0, 'Ground Tilt', 'भू-झुकाव', 'SN-LD-001', 'Evacuate immediately. Critical ground movement detected.', 'तत्काल स्थानान्तरण। महत्वपूर्ण भू-चाल पहिचान।', false),
('ALT-CRIT-003', 'SINDHUPALCHOK-05', NOW() - INTERVAL '12 minutes', 'moisture', 'CRITICAL', 92.5, 90.0, 'Soil Moisture', 'माटो चिस्यान', 'SN-LD-001', 'Soil fully saturated. Evacuation recommended.', 'माटो पूर्ण चिस्यान। स्थानान्तरण सुझाव।', false),
('ALT-HIGH-001', 'SINDHUPALCHOK-07', NOW() - INTERVAL '3 minutes', 'rainfall_instant', 'HIGH', 32.5, 30.0, 'Instant Rainfall', 'तत्काल वर्षा', 'SN-LD-002', 'Prepare evacuation. Heavy rainfall detected.', 'स्थानान्तरण तयारी। भारी वर्षा पहिचान।', false),
('ALT-HIGH-002', 'SINDHUPALCHOK-07', NOW() - INTERVAL '8 minutes', 'moisture', 'HIGH', 78.0, 75.0, 'Soil Moisture', 'माटो चिस्यान', 'SN-LD-002', 'Soil moisture elevated. Monitor closely.', 'माटो चिस्यान बढेको। नजिक अवलोकन।', false),
('ALT-HIGH-003', 'GORKHA-04', NOW() - INTERVAL '15 minutes', 'vibration', 'HIGH', 0.32, 0.30, 'Vibration', 'कम्पन', 'SN-GK-001', 'Elevated vibration. Prepare evacuation.', 'कम्पन बढेको। स्थानान्तरण तयारी।', false),
('ALT-HIGH-004', 'GORKHA-04', NOW() - INTERVAL '20 minutes', 'tilt', 'HIGH', 5.2, 5.0, 'Ground Tilt', 'भू-झुकाव', 'SN-GK-001', 'Tilt above threshold. Unstable slope.', 'झुकाव माथि। अस्थिर ढलान।', false),
('ALT-MOD-001', 'KASKI-12', NOW() - INTERVAL '30 minutes', 'moisture', 'MODERATE', 58.2, 55.0, 'Soil Moisture', 'माटो चिस्यान', 'SN-PK-001', 'Monitor moisture levels.', 'चिस्यान स्तर अवलोकन।', false);

-- Seed sensor nodes for the 3 zones with DHM stations + a few more
INSERT INTO sensors (sensor_id, zone_id, api_key, lat, lng, battery_pct, status, mode) VALUES
('SN-LD-001', 'SINDHUPALCHOK-05', 'key-ld-001', 27.8500, 85.7800, 62.0, 'active', 'elevated'),
('SN-LD-002', 'SINDHUPALCHOK-07', 'key-ld-002', 27.7800, 85.9200, 78.0, 'active', 'elevated'),
('SN-GK-001', 'GORKHA-04', 'key-gk-001', 28.0000, 84.6300, 45.0, 'active', 'normal'),
('SN-PK-001', 'KASKI-12', 'key-pk-001', 28.3500, 84.0200, 92.0, 'active', 'normal'),
('SN-NW-001', 'NUWAKOT-02', 'key-nw-001', 27.9200, 85.2700, 85.0, 'active', 'normal'),
('SN-DH-001', 'DHADHING-08', 'key-dh-001', 27.8600, 84.9100, 15.0, 'active', 'normal'),
('SN-NT-001', 'SINDHUPALCHOK-05', 'key-nt-001', 27.8550, 85.7850, 5.0, 'offline', 'normal')
ON CONFLICT (sensor_id) DO NOTHING;

-- Update sensor last_seen timestamps
UPDATE sensors SET last_seen = NOW() WHERE status = 'active';
UPDATE sensors SET last_seen = NOW() - INTERVAL '2 hours' WHERE sensor_id = 'SN-NT-001';